package DataStore;

import Sellertool.Sellertool;
import java.util.InputMismatchException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jacob
 */
public class MakeBoneDialog extends javax.swing.JDialog {
    Sellertool mySellerTool;
    String currentBone;
    Dinosaur temp = null;
    Float price;
    public Boolean goodvalue = false;
    
    
    /**
     * Creates new form MakeBoneDialog
     */
    public MakeBoneDialog(java.awt.Frame parent, boolean modal,Sellertool newSellerTool) {
        super(parent, modal);
        mySellerTool  = newSellerTool;
        goodvalue = false;
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PriceInput = new javax.swing.JTextField();
        MakeBoneTitle = new javax.swing.JLabel();
        BoneDropDown = new javax.swing.JComboBox<String>();
        button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        TextInField = new javax.swing.JTextField();

        PriceInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PriceInputActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        MakeBoneTitle.setText("MakeBones");

        BoneDropDown.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Spinosaurus", "TyrannosaurusRex", "Gigantosaurus", "Velociraptor", "Triceratops", "Hylaeosaurus", "Amargasaurus", "Dakosaurus", "Shastasaurus", "Pterodactyl", "Pterosaurs", "Pteranodon" }));
        BoneDropDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoneDropDownActionPerformed(evt);
            }
        });

        button.setText("OkieDokie");
        button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonMousePressed(evt);
            }
        });

        jLabel1.setText("PriceLabel");

        TextInField.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                TextInFieldMouseMoved(evt);
            }
        });
        TextInField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextInFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(MakeBoneTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(button))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(TextInField)
                    .addComponent(BoneDropDown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MakeBoneTitle)
                .addGap(36, 36, 36)
                .addComponent(BoneDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextInField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(button)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BoneDropDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoneDropDownActionPerformed
        // TODO add your handling code here:
         String bone = String.valueOf(BoneDropDown.getSelectedItem());
         System.out.printf("%s", bone);
         currentBone=bone;
         //change the price in a minute
    }//GEN-LAST:event_BoneDropDownActionPerformed

    private void PriceInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PriceInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PriceInputActionPerformed

    private void buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMousePressed
        // TODO add your handling code here:
        if(goodvalue == true){
        temp = mySellerTool.make_bone_prompt(-90.00, -10.00, price, currentBone);
        mySellerTool.bonelist.add(temp);
        this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(this, "INVALID");
        }
    }//GEN-LAST:event_buttonMousePressed

    private void TextInFieldMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextInFieldMouseMoved
        // TODO add your handling code here:
        try{
        price = Float.parseFloat(TextInField.getText());
        goodvalue = true;
        }
        catch(NumberFormatException | InputMismatchException e)
        {
            goodvalue = false;
        }
        
    }//GEN-LAST:event_TextInFieldMouseMoved

    private void TextInFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextInFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextInFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MakeBoneDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MakeBoneDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MakeBoneDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MakeBoneDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        /*
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MakeBoneDialog dialog;
                dialog = new MakeBoneDialog(new javax.swing.JFrame(), true, this.mySellerTool);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
*/ 
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BoneDropDown;
    private javax.swing.JLabel MakeBoneTitle;
    private javax.swing.JTextField PriceInput;
    private javax.swing.JTextField TextInField;
    private javax.swing.JButton button;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
