package DataStore;

import Sellertool.Sellertool;
import java.util.InputMismatchException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jacob
 */
public class MakeBoneDialog extends javax.swing.JDialog {
    Sellertool mySellerTool;
    String currentBone;
    Dinosaur temp = null;
    Boolean goodvalue = false;
    
    /**
     * Creates new form MakeBoneDialog
     */
    public MakeBoneDialog(java.awt.Frame parent, boolean modal,Sellertool newSellerTool) {
        super(parent, modal);
        mySellerTool  = newSellerTool;
        ErrorPopup Error = new ErrorPopup(this , true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PriceInput = new javax.swing.JTextField();
        MakeBoneTitle = new javax.swing.JLabel();
        BoneDropDown = new javax.swing.JComboBox<>();
        button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        PriceInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PriceInputActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        MakeBoneTitle.setText("MakeBones");

        BoneDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Spinosaurus", "TyrannosaurusRex", "Gigantosaurus", "Velociraptor", "Triceratops", "Hylaeosaurus", "Amargasaurus", "Dakosaurus", "Shastasaurus", "Pterodactyl", "Pterosaurs", "Pteranodon" }));
        BoneDropDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoneDropDownActionPerformed(evt);
            }
        });

        button.setText("OkieDokie");
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });

        jLabel1.setText("PriceLabel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(BoneDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(button))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(MakeBoneTitle)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MakeBoneTitle)
                .addGap(36, 36, 36)
                .addComponent(BoneDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addComponent(button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BoneDropDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoneDropDownActionPerformed
        // TODO add your handling code here:
         String bone = String.valueOf(BoneDropDown.getSelectedItem());
         currentBone=bone;
         //change the price in a minute
         
    }//GEN-LAST:event_BoneDropDownActionPerformed

    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed
        // TODO add your handling code here:
       if(goodvalue){
           temp = mySellerTool.make_bone_prompt(0.0,0.0,400.0f,this.currentBone);
       }
       else{
           //call popup
       }
    }//GEN-LAST:event_buttonActionPerformed

    private void PriceInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PriceInputActionPerformed
        // TODO add your handling code here:
       
        
        if (temp== null){
            //call pop up
            goodvalue = false;
        }
        else{
            try{
                temp.price = Float.parseFloat(PriceInput.getText());
                goodvalue = true;
                
            }catch(NumberFormatException | InputMismatchException e){
                //call pop up
                goodvalue = false;
            }
        }
    }//GEN-LAST:event_PriceInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MakeBoneDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MakeBoneDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MakeBoneDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MakeBoneDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        /*
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MakeBoneDialog dialog;
                dialog = new MakeBoneDialog(new javax.swing.JFrame(), true, this.mySellerTool);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
*/ 
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BoneDropDown;
    private javax.swing.JLabel MakeBoneTitle;
    private javax.swing.JTextField PriceInput;
    private javax.swing.JButton button;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
