/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DataStore;

import Sellertool.Sellertool;
import java.util.ArrayList;
import java.util.InputMismatchException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Jacob
 */
public class ModifyBone extends javax.swing.JDialog {
        Sellertool inhere;
        public ArrayList<String> pop = new ArrayList<>();//used to put ID in box
        int i;
        Dinosaur temp;
        int DBselection;
        int IDselection = 0;
        Boolean tempselected = false;
        Boolean IDselected = false;
        Boolean OperationSelected = false;
        float price =0;
        
    /**
     * Creates new form ModifyBone
     */
    public ModifyBone(java.awt.Frame parent, boolean modal,Sellertool GUISellertool) {
        super(parent, modal);
        inhere = GUISellertool;
       for(i = 0 ; i < inhere.bonelist.size(); i++){    //generates and populate the dropbox
           pop.add(Integer.toString(inhere.bonelist.get(i).boneID));
        }
        initComponents();
        IDComboBox.setModel(new DefaultComboBoxModel(pop.toArray()));
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IDComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        SelectionComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        PriceInputField = new javax.swing.JTextField();
        OKbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        IDComboBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                IDComboBoxFocusLost(evt);
            }
        });

        jLabel1.setText("Bone #ID");

        SelectionComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Change Price", "Change Location", "Sell Bone" }));
        SelectionComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectionComboBoxActionPerformed(evt);
            }
        });

        jLabel2.setText("Field");

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel3.setText("ModifyField");

        PriceInputField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                PriceInputFieldFocusLost(evt);
            }
        });

        OKbutton.setText("OKieDokie");
        OKbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(60, 60, 60))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(IDComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SelectionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(OKbutton)
                        .addComponent(PriceInputField, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SelectionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(PriceInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(OKbutton)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SelectionComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectionComboBoxActionPerformed
        // TODO add your handling code here:
         //if button activated
         DBselection = SelectionComboBox.getSelectedIndex(); //sets box to change price , Location, or BuyingStatus
         OperationSelected = true;
         System.out.printf("%s", "Operation selected\n");
    }//GEN-LAST:event_SelectionComboBoxActionPerformed

    private void OKbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKbuttonActionPerformed
        // TODO add your handling code here:
        Boolean invalid = false;
        if(OperationSelected & tempselected){
            
            if((DBselection == 0)&& (price > 0)){                       //changes the price
                temp.price = this.price;
                 System.out.printf("%f%n", temp.price);
                 inhere.printbonelist();
                 this.dispose();
            }
            if(DBselection == 1){
                while(!invalid){//translates while truely invalid                       //gets the coordinates in comma form
                    String StrArra[];
                    String Strcoord = JOptionPane.showInputDialog("Enter Corrdinates");
                    StrArra = Strcoord.split(",");
                    try{
                        temp.coordinates.latit = Double.valueOf(StrArra[0]);
                        temp.coordinates.longi = Double.valueOf(StrArra[1]);
                        invalid = true;  //translates no longer invalid
                    }catch(NumberFormatException | InputMismatchException e){
                        JOptionPane.showMessageDialog(this, e);
                    }
                
                }//while
                inhere.printbonelist();
                this.dispose();
            }
            if(DBselection == 2){           //switch value of bought to change from sold to unsold and vice versa
               System.out.printf("%d%n",temp.bought);
               if(temp.bought == 0){
                   temp.bought = 1;}
               else{
                   temp.bought =0;}
               System.out.printf("%d%n",temp.bought);
               this.dispose();
            }
                
        }
        else{
            JOptionPane.showMessageDialog(this,"Finish Selction Make One");
            inhere.printbonelist();
          
        }
    }//GEN-LAST:event_OKbuttonActionPerformed
    private void IDComboBoxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_IDComboBoxFocusLost
        // TODO add your handling code here:
        IDselection = IDComboBox.getSelectedIndex();  //gets index of sele DrBx item and associates to temp
        temp  = inhere.bonelist.get(IDselection);
        tempselected = true;
        System.out.printf("%s", "ID selected\n");
    }//GEN-LAST:event_IDComboBoxFocusLost

    private void PriceInputFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PriceInputFieldFocusLost
        // TODO add your handling code here:
           
        try{ 
           price = Float.valueOf(PriceInputField.getText());
           System.out.printf("%f%n", price);
       }catch(NumberFormatException | InputMismatchException e){
           JOptionPane.showInputDialog("Bad Input");
       }
     
    }//GEN-LAST:event_PriceInputFieldFocusLost

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifyBone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifyBone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifyBone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifyBone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
       /* java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ModifyBone dialog = new ModifyBone(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox IDComboBox;
    private javax.swing.JButton OKbutton;
    private javax.swing.JTextField PriceInputField;
    private javax.swing.JComboBox SelectionComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
