/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DataStore;

import Sellertool.Seller;
import Sellertool.Sellertool;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Formatter;
import java.util.InputMismatchException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Jacob
 */
public class SellerPrompt extends javax.swing.JDialog {
    //Seller temp = new Seller(0);//blank seller to pass to array list in GUISellerlist
    Sellertool inhere; //pointer to GUI seller
    Seller temp = new Seller(0); 
    String field;
    Scanner input = new Scanner(System.in);
    Formatter output = new Formatter(System.out);
    Boolean name_entered = false;
    Boolean latitude_entered = false;  //booleans to create seller
    Boolean longitude_entered = false;
    String name;
    Double latitude = 200.;
    Double longitude = 300.;
    
    /**
     * Creates new form SellerPrompt
     */
    public SellerPrompt(java.awt.Frame parent, boolean modal, Sellertool GUISellertool) {
        super(parent, modal);
        inhere = GUISellertool;
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        GetNameField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        GetLatitudeField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        GetLongitudeField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel1.setText("Seller Creation");

        jButton1.setText("OkieDokie");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        GetNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                GetNameFieldFocusLost(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("AR JULIAN", 0, 12)); // NOI18N
        jLabel3.setText("Name");

        GetLatitudeField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                GetLatitudeFieldFocusLost(evt);
            }
        });
        GetLatitudeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetLatitudeFieldActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("AR JULIAN", 0, 12)); // NOI18N
        jLabel4.setText("Latitude");

        GetLongitudeField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                GetLongitudeFieldFocusLost(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("AR JULIAN", 0, 12)); // NOI18N
        jLabel5.setText("Longitude");

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(8, 8, 8)))
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(GetNameField)
                    .addComponent(GetLatitudeField)
                    .addComponent(GetLongitudeField, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GetNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GetLatitudeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GetLongitudeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(latitude_entered & longitude_entered & name_entered)
        {   
            temp = new Seller(this.name,this.latitude,this.longitude);                    
            inhere.masterlist.add(temp);
            System.out.printf("%n%s %f|%f%n",temp.name,temp.coordinate.latit,temp.coordinate.longi);
            inhere.writesellerfile();
            this.dispose();
        }
        else{
            JOptionPane.showInputDialog("Enter all fields Try Again");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void GetLatitudeFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_GetLatitudeFieldFocusLost
        // TODO add your handling code here:
          field = null;
          field = GetLatitudeField.getText().trim(); //gets string
        do{
        try{
            this.latitude = Double.valueOf(field);
            System.out.printf("%f", longitude);            
            this.latitude_entered = true;
        }catch(NumberFormatException | InputMismatchException | NullPointerException e){
            //JOptionPane.showInputDialog(e);
             field = (JOptionPane.showInputDialog("re-enter Latitude"));
            }
        if((this.latitude)>90 || (this.latitude <-90)){
            field = (JOptionPane.showInputDialog("re-enter Latitude"));
        }
        }while((this.latitude)>90 || (this.latitude <-90));
    }//GEN-LAST:event_GetLatitudeFieldFocusLost

    private void GetNameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_GetNameFieldFocusLost
        //get the name from field
      field = GetNameField.getText().trim();
      this.name = field;
      name_entered = true;
      //output.format("PRINt", null);
    }//GEN-LAST:event_GetNameFieldFocusLost

    private void GetLongitudeFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_GetLongitudeFieldFocusLost
        // TODO add your handling code here:
        field = null;
        field = GetLongitudeField.getText().trim(); //gets string
        do{
         try{this.longitude = Double.valueOf(field);
            longitude_entered = true;
            output.format("*%f*",longitude);
           
        }catch(NumberFormatException | InputMismatchException | NullPointerException e){
            //JOptionPane.showInputDialog(e);
            field = (JOptionPane.showInputDialog("re-enter Longitude"));            
            }
          if((this.longitude>180) || (this.longitude <-180)){
            field = (JOptionPane.showInputDialog("re-enter Longitude"));
            }
       }while(this.longitude<-180 || this.longitude>180);
    }//GEN-LAST:event_GetLongitudeFieldFocusLost

    private void GetLatitudeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetLatitudeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GetLatitudeFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SellerPrompt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SellerPrompt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SellerPrompt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SellerPrompt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        /*
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SellerPrompt dialog = new SellerPrompt(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        }
        );
        */
  }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField GetLatitudeField;
    private javax.swing.JTextField GetLongitudeField;
    private javax.swing.JTextField GetNameField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
